### ISSUE TITLE
npm availability

### ISSUE THREAD

**Issue by niranjan404** [Justineo/highlightable-input#2]
Is this code available as npm package for react? I am interest to integrate this input to my app, and also can use my input element with this?

Thanks @Justineo

**Comment by Justineo** [comment]
https://github.com/Justineo/highlightable-input#react-component

**Comment by niranjan404** [comment]
> https://github.com/Justineo/highlightable-input#react-component

Can you provide npm package link? i couldn't find with name "highlightable-input" that's my query.
