### ISSUE TITLE
npm availability

### ISSUE THREAD

**Issue by harshitKRVishwakarma** [Justineo/highlightable-input#3]

**Comment by Justineo** [comment]
It *is* available on npm.

**Comment by harshitKRVishwakarma** [comment]
What's the name of the package, it would be helpful if you can provide the link to it.

**Comment by Justineo** [comment]
See https://github.com/Justineo/highlightable-input#basic-usage

**Comment by harshitKRVishwakarma** [comment]
Sorry for the confusion, I am looking for npm i <package_name>

**Comment by Justineo** [comment]
Okay maybe I can add an installation part to the readme later.
