### ISSUE TITLE
Disable console.log() on content change

### ISSUE THREAD

**Issue by mxlauc** [Justineo/highlightable-input#4]
I'm using the component for Vue.
When text is edited, the content is shown in console.log(). There is no prop to disable it. Could you remove it?

This behavior can be seen at: https://highlightable-input.vercel.app/

![image](https://github.com/Justineo/highlightable-input/assets/25208794/136de9b3-d85b-4d9e-9026-3094e7a2c612)

**Comment by Justineo** [comment]
Fixed in v0.2.3.
